### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Sabrinasaunders** [Sabrinasaunders/outfit-organizer#1]
AS a stylish person
I WANT a program that can organize my outfits
SO THAT I can save time trying to pick what clothes to wear

GIVEN THAT I'm an authenticated user
WHEN I search for an outfit to wear
THEN I am given a few options of outfits to wear

**Comment by Aoliva96** [comment]
WHEN I want to sort my clothing
THEN I am shown a filtered list of my clothing by type and color
